feat: Add a state-sync guide
dymensionxyz/docs pull request #249
Opened 2023-10-12 09:55 UTC by ItayLevyOfficial

2023-10-17 08:24 UTC, omritoptix requested changes

2023-10-17 08:24 UTC, omritoptix commented on docs/build/custom-configuration.mdx
> +        to <a href={"state_sync#create-a-snapshot"}>take a snapshot</a> of the rollapp
why is it necessary to take a snapshot before?

2023-10-17 08:24 UTC, omritoptix commented on docs/build/quick-start/roller-quick/initialize.mdx
> +Not recommended for production rollapps since resync won't work.</div>
this is not the only reason. this line can be removed. it's simply not secure.

2023-10-17 08:24 UTC, omritoptix commented on docs/build/quick-start/roller-quick/initialize.mdx
> +Not recommended for production rollapps since resync won't work.</div>
remove. redundant. see my previous comment.

2023-10-17 08:24 UTC, omritoptix commented on docs/build/state-sync.mdx
> +1. The rollapp is using a genuine DA layer (Celestia/Avail) and not a local one.
1. no need to mention the rollapp needs to use a real or mock da layer. it actually works with both if it's for development purposes.

2023-10-17 08:24 UTC, omritoptix commented on docs/build/state-sync.mdx
> +2. The snapshot has been taken less than 30 days ago.
again. no need to write it currently. when we'll get to production we'll do it much more detailed. currently celestia keep the entire data. not sure about avail.

2023-10-17 08:26 UTC, mtsitrin commented on docs/build/custom-configuration.mdx
> +    before performing this operation.</div>
@ItayLevyOfficial why before?
u probably prefer to make a snapshot **after** the da change

2023-10-17 14:48 UTC, ItayLevyOfficial commented on docs/build/custom-configuration.mdx
> +    before performing this operation.</div>
No - the snapshot include only the rollapp data directory, which is not being changed in the change DA procedure - which updates only the config

2023-10-17 14:50 UTC, ItayLevyOfficial commented on docs/build/state-sync.mdx
> +2. The snapshot has been taken less than 30 days ago.
I still think it's good to keep it here as this is their plan

2023-10-17 15:59 UTC, omritoptix commented on docs/build/custom-configuration.mdx
> +        to <a href={"state_sync#create-a-snapshot"}>take a snapshot</a> of the rollapp
you mean that the act of changing da caused data corruption?

2023-10-17 16:01 UTC, omritoptix commented on docs/build/state-sync.mdx
> +1. The rollapp is using a genuine DA layer (Celestia/Avail) and not a local one.
are you sure? the data directory supposed to contain all the relevant state. why should it be related?

2023-10-17 16:02 UTC, omritoptix commented on docs/build/state-sync.mdx
> +2. The snapshot has been taken less than 30 days ago.
yea but this docs are not for production and also we don't know their exact plan and also we don't know avail plan so anyway all of this is very development/froopyland oriented. so better not partial/wrong information currently. when the time comes for real rollapps on mainnet will have much more extensive documentation. this is mostly for testnet currently.

2023-10-17 16:39 UTC, mtsitrin commented on docs/build/custom-configuration.mdx
> +    before performing this operation.</div>
but others won't be able to sync from this snapshot

2023-10-18 14:34 UTC, omritoptix commented on docs/build/quick-start/roller-quick/initialize.mdx
> +Not recommended for production rollapps since resync won't work.</div>
I see you removed the entire "local da" line. sorry if I wasn't clear. ment only this line:

`Not recommended for production rollapps since resync won't work.</div>`

2023-10-18 14:39 UTC, ItayLevyOfficial commented on docs/build/custom-configuration.mdx
> +        to <a href={"state_sync#create-a-snapshot"}>take a snapshot</a> of the rollapp
No - The data got corrupted because the sequencer suddenly stopped. It can happen if the machine being turned off or something like this

2023-10-18 14:39 UTC, ItayLevyOfficial commented on docs/build/custom-configuration.mdx
> +        to <a href={"state_sync#create-a-snapshot"}>take a snapshot</a> of the rollapp
And if this happens you need to re-sync the rollapp - which is only possible if you took a snapshot before changing DA

2023-10-18 14:53 UTC, ItayLevyOfficial commented on docs/build/state-sync.mdx
> +1. The rollapp is using a genuine DA layer (Celestia/Avail) and not a local one.
Because even if the data directory contain all the data, it won't be able to fetch transaction batches that created afterwards from the DA

2023-10-18 15:15 UTC, merged